#!/usr/bin/env python3
"""
Script per estrarre cookies di Facebook dal browser
Esegui questo script DOPO aver fatto login su Facebook
"""

from playwright.sync_api import sync_playwright
import os

def extract_facebook_cookies():
    print("🍪 Estrazione cookies Facebook...")
    print("=" * 50)
    
    with sync_playwright() as p:
        # Lancia browser con interfaccia grafica
        browser = p.chromium.launch(headless=False)
        context = browser.new_context(
            user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36'
        )
        page = context.new_page()
        
        # Vai su Facebook
        print("🌐 Navigando su Facebook...")
        page.goto("https://www.facebook.com")
        
        print("\n" + "="*50)
        print("📱 FAI LOGIN MANUALMENTE su Facebook nella finestra del browser")
        print("✅ Assicurati di essere loggato e di vedere la home di Facebook")
        print("⏳ Premi INVIO quando hai completato il login...")
        print("="*50)
        input()
        
        # Estrai cookies
        print("🔍 Estrazione cookies in corso...")
        cookies = context.cookies()
        
        # Filtra solo cookies Facebook
        fb_cookies = [c for c in cookies if 'facebook.com' in c['domain']]
        
        if not fb_cookies:
            print("❌ Nessun cookie Facebook trovato!")
            print("💡 Assicurati di aver fatto login correttamente")
            browser.close()
            return
        
        # Salva in formato Netscape
        print(f"💾 Salvando {len(fb_cookies)} cookies...")
        
        with open('cookies.txt', 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by extract_cookies.py\n")
            f.write("# Domain\tFlag\tPath\tSecure\tExpires\tName\tValue\n")
            
            for cookie in fb_cookies:
                domain = cookie['domain']
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie['path']
                secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
                expires = int(cookie.get('expires', 0))
                name = cookie['name']
                value = cookie['value']
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        print("✅ Cookies salvati con successo in 'cookies.txt'")
        print("📤 Ora puoi caricare questo file nel tuo repository GitHub")
        
        browser.close()

if __name__ == "__main__":
    try:
        extract_facebook_cookies()
    except KeyboardInterrupt:
        print("\n❌ Operazione annullata dall'utente")
    except Exception as e:
        print(f"❌ Errore: {e}")
        print("💡 Assicurati di aver installato playwright: pip install playwright")
