name: Estrai & Invia Menu Quotidiano

on:
  schedule:
    # Ogni 10 minuti dalle 8:00 alle 11:50 (ora italiana = UTC+1)
    - cron: '0,10,20,30,40,50 7 * * *'
    - cron: '0,10,20,30,40,50 8 * * *'
    - cron: '0,10,20,30,40,50 9 * * *'
    - cron: '0,10,20,30,40,50 10 * * *'
  workflow_dispatch: # Permette esecuzione manuale

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright schedule requests Pillow

    - name: Install Playwright browsers
      run: |
        playwright install chromium
        playwright install-deps chromium

    - name: Run script
      env:
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      run: python fantasia.py
